version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            gem install bundler:2.3.18
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results

  deploy:
    docker:
      - image: cimg/ruby:3.1.2

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            gem install bundler:2.3.18
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: build release
          command: bundle exec rake build

      - run:
          name: push gem release
          command: |
            gem push pkg/ostiary*.gem

workflows:
  version: 2
  CircleCI:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/

      - deploy:
          context:
            - Github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+([\w\.]+)?$/ # Support prereleases, see https://guides.rubygems.org/patterns/#prerelease-gems
